### ISSUE TITLE
Feature Request: Make enum casing configurable

### ISSUE THREAD

**Issue by lazylazyllama** [comigor/artemis#122]
Right now the enums generated by artemis are all like this: "ENUM_EXAMLE"

Im not sure if this is because of what my api is sending artemis or if artemis generally makes enums look like this. But it doesn't matter after all.

There is a package called: https://pub.dev/packages/recase

With this it could be made configurable which style enums should have.

In dart by default enums are "camelcase" ... so I think camelcase should be made default in the next major release.

**Comment by comigor** [comment]
Hello again @lazylazyllama!

Actually Artemis won't do any case conversion to enums, so the "default" is `SCREAMING_SNAKE_CASE` because that's the GraphQL default (if your GraphQL server returned it as `camelCase`, it would be generated as so).

But since effective dart points the usage of `camelCase` as default for enums (as seen on https://dart-lang.github.io/linter/lints/constant_identifier_names.html), I agree they  should be the default on Artemis as well!

**Comment by preetjdp** [comment]
Hey Just tried https://github.com/comigor/artemis/pull/141 on my project and looks to be failing.

The type of the enum is showing up as `artemisUnknown`
My enums are in this format.

```
enum State{
  CREATED
  DECLINED
  ACKNOWLEDGED
  PAID
}
```

@lazylazyllama could the Enums type casing me configurable rather than a enforced camelCase?

**Comment by lazylazyllama** [comment]
Hmm I can not reproduce this .. I have a very big schema and everything is working perfectly fine in my case. My enums are formatted the same way yours are.

So can you give some further information about what is actually happening? As I am a little bit confused right know.
Artemis always adds artemisUnknown as a additional value to every enum. That is normal if that is what you mean?


To your second point: I think I do agree, that making it configurable would be a nice thing to have. I think graphql codegen for typescript etc. is already doing that aswell. But right now I don't have enough time to add that. So I only made artemis convert anything into camel case as this is the default enum casing for dart.

**Comment by ram231** [comment]
How about a linter to ignore SCREAMING_CASE for enum in our analysis_options.dart. In that way, we could align the graphql specs to our dart code. Seriously, graphql and dart have both different worlds and different preferences.

**Comment by preetjdp** [comment]
Hey @lazylazyllama here's one project where Enums casting is failing.
https://github.com/preetjdp/YouOweMe/tree/upgrade-artemis/mobileApp

On looking further the problem seems to be with the `EnumMap` Generated
```dart
const _$OweStateEnumMap = {
  OweState.created: 'created',
  OweState.declined: 'declined',
  OweState.acknowledged: 'acknowledged',
  OweState.paid: 'paid',
  OweState.artemisUnknown: 'artemisUnknown',
};
```

Changing the above to makes everything work
```dart 
const _$OweStateEnumMap = {
  OweState.created: 'CREATED',
  OweState.declined: 'DECLINED',
  OweState.acknowledged: 'ACKNOWLEDGED',
  OweState.paid: 'PAID',
  OweState.artemisUnknown: 'artemisUnknown',
};
```
URL for the same ==>

https://github.com/preetjdp/YouOweMe/blob/906db32382dd814830058c0702187bc469c4f82a/mobileApp/lib/resources/graphql/seva.graphql.g.dart#L95-L101

Below are the files that may be useful to debug the problem.

**The Build.yaml File**
https://github.com/preetjdp/YouOweMe/blob/upgrade-artemis/mobileApp/build.yaml

**The Schema File**
https://github.com/preetjdp/YouOweMe/blob/upgrade-artemis/mobileApp/lib/resources/graphql/youoweme.schema.graphql

**The Query that I make**
https://github.com/preetjdp/YouOweMe/blob/upgrade-artemis/mobileApp/lib/resources/graphql/queries/me.graphql

**Comment by lazylazyllama** [comment]
Okay thank you very much :) I will have a look on it later this day

**Comment by vasilich6107** [comment]
Hi
Could you try this branch while it awaits the review?
```
artemis:
    git:
      url: https://github.com/comigor/artemis.git
      ref: bugfix/underscored-items-another-solution
```

**Comment by vasilich6107** [comment]
@lazylazyllama we adjusted the enum casing according to dart specs. If it fits your needs this issue could be closed.
