### ISSUE TITLE
How do I provide arguments to a query?

### ISSUE THREAD

**Issue by martinolsson** [comigor/artemis#168]
Sorry if this is the wrong place to ask questions.

I'm trying to use Artemis 5.1.0 and I'm having trouble understanding how to provide an argument to a query. My query looks like this:

```
query Thing($id: ID!) {
  thing(id: $id) {
    name
    id
  }
}
```

I generate types and helpers, and try to use sort of like this (simplified):

```
import 'package:graphql_flutter/graphql_flutter.dart';
GraphQLClient client;

Future<Thing> getThing(String id) async {
  final ThingArguments thingArguments = ThingArguments(id: id);
  final WatchQueryOptions _options = WatchQueryOptions(
    documentNode: ThingQuery(variables: thingArguments).document,
    pollInterval: 4,
    fetchResults: true,
  );

  final QueryResult result = await client.query(_options);
}

```
But the result has an exception: **Variable “$id” of required type “ID!” was not provided.: Undefined location**

I've made sure that the id is in fact provided, so I must be doing something else wrong. Do I have to use the ArtemisClient instead of the graphql_flutter client? There are no examples that I can find where an argument to a query is used.

**Comment by comigor** [comment]
Hey @martinolsson, how are you doing?

We're currently focusing efforts into the [**beta**](https://github.com/comigor/artemis/tree/beta) branch, because a lot of breaking changes can happen/already happened there without many consequences. The idea is to eventually merge it into master. Beta branch is a lot more advanced than master, with a lot of bugfixes.

Could you try to use the same schema/query on beta ([6.4.3-beta.1](https://pub.dev/packages/artemis/versions/6.4.3-beta.1) is currently the latest version)? graphql_flutter client should work without issues!

**Comment by martinolsson** [comment]
Thank you for getting back to me. I found why my code was not working, and it had nothing to do with artemis - both 5.1.0 and 6.4.3-beta.1 work. The problem was that I was not adding the id variable to the query in the correct way. I thought adding the "ThingArguments" (code above) to the query would add the id I supplied, so I did not add it to the QueryOptions as a variable. Changing the above code to the following did the trick:
