### ISSUE TITLE
Flutter 2.2.0 with Dart 2.13

### ISSUE THREAD

**Issue by ramyak-mehra** [comigor/artemis#312]
Since flutter 2.2.0 comes with 2.13 it supports type alias. This can be used to avoid the usage of fragments in nested queries resulting in mixins which we have to sometimes cast to the original class name

**Comment by comigor** [comment]
Hi @ramyak-mehra,
Indeed I was expecting this feature to help with fragments and even canonical types matching/transformation per-schema. Even without any automatic change from Artemis, type alias could already be used to "prettify" the usage of Artemis, specially when you're using `pathedWithTypes` naming scheme.

**Comment by ramyak-mehra** [comment]
I would like to contribute to it if you could guide me a bit from where should i start.

**Comment by comigor** [comment]
So one of the goals I have is to make Artemis output "canonical" classes (based on the configured GraphQL schema rather than queries selection sets). And, by creating that, one could "convert" a class that comes as a result of a query: let's say, exemplifying, `Query$Query$People` to its canonical counterpart `Person`. Part of this idea was exposed [here](https://github.com/comigor/artemis/discussions/244). Currently, this behaviour already exists, but solely with the use of fragments across multiple queries.

Anyway, now users could `Query$Query$People` classes can now be aliased to `Person` without too much effort when you don't want to deal with long names.

>This can be used to avoid the usage of fragments in nested queries resulting in mixins which we have to sometimes cast to the original class name

I don't see where type aliases can help with this. Sometimes we do want to have a mixin for fragments so they can be used as a interface for the same class coming from different queries or selections.

**Comment by ramyak-mehra** [comment]
> So one of the goals I have is to make Artemis output "canonical" classes (based on the configured GraphQL schema rather than queries selection sets). And, by creating that, one could "convert" a class that comes as a result of a query: let's say, exemplifying, `Query$Query$People` to its canonical counterpart `Person`. Part of this idea was exposed [here](https://github.com/comigor/artemis/discussions/244). Currently, this behaviour already exists, but solely with the use of fragments across multiple queries.
> 
> Anyway, now users could `Query$Query$People` classes can now be aliased to `Person` without too much effort when you don't want to deal with long names.
> 
> >This can be used to avoid the usage of fragments in nested queries resulting in mixins which we have to sometimes cast to the original class name
> 
> I don't see where type aliases can help with this. Sometimes we do want to have a mixin for fragments so they can be used as a interface for the same class coming from different queries or selections.

Currently this went over my head 😂 but I think it's great place to start I'll spend some more time with this. Thanks for the update though 😀

**Comment by vasilich6107** [comment]
@ramyak-mehra If we have no better idea to name classes the aliases won’t be a silver bullet

**Comment by vasilich6107** [comment]
Closing this issue as far as we could not benefit from typedefs
